### ISSUE TITLE
Content-Type header for streaming responses?

### ISSUE THREAD

**Issue by bastibense** [haileys/axum-range#1]
I'm trying to use axum-range in my project in order to support the Range header for video streaming from my backend.

Apparently I need to set the Content-Type header of the response to the correct one, depending on the file I'm serving.

How do I set the Content-Type header for the response?

**Comment by haileys** [comment]
Hello Bastian,

You can set any extra headers the usual way by returning a type that implements axum's [`IntoResponse`](https://docs.rs/axum/latest/axum/response/trait.IntoResponse.html) trait.

This crate's `Ranged<T>` type itself implements `IntoResponse`.

There also blanket implementations of `IntoResponse` which allow you to add extra response parts on top of another `IntoResponse`, for example:

```rust
fn respond() -> impl IntoResponse {
    let ranged_body = todo!();
    ([("content-type", "video/mp4")], ranged_body)
}
```

See the [`axum::response` documentation](https://docs.rs/axum/latest/axum/response/index.html) for more details.
