### ISSUE TITLE
update axum 0.7

### ISSUE THREAD

**Issue by wefcdse** [haileys/axum-range#2]
I'm trying to use the crate in my project but the crate seems not to work with axum 0.7, so I made a fork and updated the dependences to axum 0.7.2.
https://github.com/wefcdse/axum-range
axum 0.7 have some break change, and I changed one of the tests
should I make a PR?

**Comment by haileys** [comment]
Thank you for letting me know! I have just cut [`v0.4.0`](https://github.com/haileys/axum-range/tree/v0.4.0) which supports axum 0.7.

I encountered the same test failure you did, it turns out axum-range's behaviour for unbounded-start ranges was actually wrong, so that's also fixed now :)
